#!/usr/bin/python3
import pdfplumber
import sys
from gtts import gTTS

language = 'en'


def read_book(book):
    pdf = pdfplumber.open(book)
    for page in pdf.pages:
        text = page.extract_text()
    return text


def speak(text):
    tts = gTTS(text=text, lang=language, slow=False)
    tts.save('book.mp3')


if __name__ == '__main__':
    book = sys.argv[1]
    text = read_book(book)
    speak(text)
    print('Your Book is ready')
